"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import {
  ArrowLeft,
  TrendingUp,
  TrendingDown,
  Star,
  FileText,
  CheckCircle,
  XCircle,
  Lightbulb,
  Download,
  Home,
} from "lucide-react";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api";

interface Feedback {
  overall: string;
  strengths: string[];
  weaknesses: string[];
  rating: number;
  technicalScore?: number;
  problemSolvingScore?: number;
  communicationScore?: number;
  suggestions: string;
}

interface Session {
  _id: string;
  jobDetails: {
    title: string;
    description: string;
    yoeRequired: string;
  };
  status: string;
  feedback: Feedback;
  createdAt: string;
  conversation: Array<{
    role: string;
    content: string;
    timestamp: string;
  }>;
}

export default function FeedbackPage() {
  const router = useRouter();
  const params = useParams();
  const sessionId = params.sessionId as string;

  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const getAuthToken = () => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("accessToken");
    }
    return null;
  };

  const fetchSessionFeedback = async () => {
    try {
      const token = getAuthToken();
      if (!token) {
        router.push("/login");
        return;
      }

      const response = await fetch(`${API_BASE}/sessions/${sessionId}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (response.status === 401) {
        localStorage.removeItem("accessToken");
        localStorage.removeItem("refreshToken");
        router.push("/login");
        return;
      }

      if (!response.ok) {
        throw new Error("Failed to fetch feedback");
      }

      const data = await response.json();

      if (data.status !== "completed") {
        setError("This interview has not been completed yet");
        return;
      }

      if (!data.feedback) {
        setError("Feedback is not available for this session");
        return;
      }

      setSession(data);
    } catch (err: any) {
      setError(err.message || "Failed to load feedback");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (sessionId) {
      fetchSessionFeedback();
    }
  }, [sessionId]);

  const getRatingColor = (rating: number) => {
    if (rating >= 8) return "text-[#10b981]";
    if (rating >= 6) return "text-[#f9b17a]";
    if (rating >= 4) return "text-[#f59e0b]";
    return "text-[#ef4444]";
  };

  const getRatingLabel = (rating: number) => {
    if (rating >= 9) return "Excellent";
    if (rating >= 8) return "Very Good";
    if (rating >= 7) return "Good";
    if (rating >= 6) return "Above Average";
    if (rating >= 5) return "Average";
    if (rating >= 4) return "Below Average";
    if (rating >= 3) return "Needs Improvement";
    return "Poor";
  };

  const getScoreColor = (score: number) => {
    if (score >= 8) return "bg-[#10b981]";
    if (score >= 6) return "bg-[#f9b17a]";
    if (score >= 4) return "bg-[#f59e0b]";
    return "bg-[#ef4444]";
  };

  const getScoreTextColor = (score: number) => {
    if (score >= 8) return "text-[#10b981]";
    if (score >= 6) return "text-[#f9b17a]";
    if (score >= 4) return "text-[#f59e0b]";
    return "text-[#ef4444]";
  };

  const downloadFeedback = () => {
    if (!session) return;

    const advancedScores = session.feedback.technicalScore || session.feedback.problemSolvingScore || session.feedback.communicationScore
      ? `
DETAILED SCORES
---------------
${session.feedback.technicalScore ? `Technical Knowledge: ${session.feedback.technicalScore}/10` : ''}
${session.feedback.problemSolvingScore ? `Problem Solving: ${session.feedback.problemSolvingScore}/10` : ''}
${session.feedback.communicationScore ? `Communication: ${session.feedback.communicationScore}/10` : ''}
` : '';

    const feedbackText = `
Interview Feedback Report
========================

Position: ${session.jobDetails.title}
Date: ${new Date(session.createdAt).toLocaleDateString()}
Overall Rating: ${session.feedback.rating}/10 - ${getRatingLabel(session.feedback.rating)}
${advancedScores}
OVERALL ASSESSMENT
-----------------
${session.feedback.overall}

STRENGTHS
---------
${session.feedback.strengths.map((s, i) => `${i + 1}. ${s}`).join("\n")}

AREAS FOR IMPROVEMENT
--------------------
${session.feedback.weaknesses.map((w, i) => `${i + 1}. ${w}`).join("\n")}

SUGGESTIONS FOR IMPROVEMENT
---------------------------
${session.feedback.suggestions}

---
Generated by AI Mock Interview Platform
    `.trim();

    const blob = new Blob([feedbackText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `interview-feedback-${sessionId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#f8f9fa] to-white flex items-center justify-center">
        <div className="bg-white border-2 border-[#e9ecef] rounded-2xl p-12 shadow-xl">
          <div className="text-center">
            <div className="w-16 h-16 border-4 border-[#e9ecef] border-t-[#f9b17a] mx-auto mb-6 rounded-full animate-spin"></div>
            <p className="text-lg font-medium text-[#676f9d]">Loading feedback...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#f8f9fa] to-white flex items-center justify-center p-6">
        <div className="bg-white border-2 border-[#ef4444] max-w-md w-full rounded-2xl shadow-xl overflow-hidden">
          <div className="border-b-2 border-[#ef4444] p-6 flex items-center gap-4 bg-[#ef4444]/5">
            <div className="w-12 h-12 bg-[#ef4444] rounded-full flex items-center justify-center">
              <XCircle className="w-6 h-6 text-white" />
            </div>
            <h2 className="text-2xl font-bold text-[#2d3250]">Error</h2>
          </div>
          <div className="p-8">
            <p className="text-[#676f9d] mb-8 leading-relaxed">{error}</p>
            <button
              onClick={() => router.push("/dashboard")}
              className="w-full py-3 bg-[#f9b17a] hover:bg-[#e89b5f] text-white transition-all font-semibold rounded-xl"
            >
              Return to Dashboard
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!session) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#f8f9fa] to-white">
      {/* Header */}
      <header className="border-b border-[#e9ecef] sticky top-0 z-10 bg-white/95 backdrop-blur-md shadow-sm">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <button
              onClick={() => router.push("/dashboard")}
              className="p-2.5 border-2 border-[#676f9d] hover:bg-[#676f9d] text-[#676f9d] hover:text-white rounded-lg transition-all"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-2xl font-bold text-[#2d3250]">Interview Feedback</h1>
              <p className="text-sm text-[#676f9d] mt-0.5">{session.jobDetails.title}</p>
            </div>
          </div>
          <div className="flex gap-3">
            <button
              onClick={downloadFeedback}
              className="px-5 py-2.5 border-2 border-[#e9ecef] hover:border-[#f9b17a] hover:bg-[#f9b17a]/5 text-[#676f9d] hover:text-[#f9b17a] transition-all flex items-center gap-2 font-medium rounded-lg"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Download</span>
            </button>
            <button
              onClick={() => router.push("/dashboard")}
              className="px-5 py-2.5 bg-[#424769] text-white hover:bg-[#2d3250] transition-all flex items-center gap-2 font-medium rounded-lg"
            >
              <Home className="w-4 h-4" />
              <span className="hidden sm:inline">Dashboard</span>
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-12">
        {/* Rating Card */}
        <div className="bg-white border-2 border-[#e9ecef] rounded-3xl p-12 mb-8 relative overflow-hidden shadow-lg">
          <div className="absolute top-0 right-0 w-32 h-32 border-l-4 border-b-4 border-[#f9b17a]/10 rounded-bl-3xl"></div>
          <div className="absolute bottom-0 left-0 w-32 h-32 border-r-4 border-t-4 border-[#676f9d]/10 rounded-tr-3xl"></div>

          <div className="flex flex-col md:flex-row items-center justify-between gap-8 relative z-10">
            <div className="flex items-center gap-6">
              <div className="w-24 h-24 bg-gradient-to-br from-[#f9b17a]/10 to-[#f9b17a]/5 rounded-2xl border-2 border-[#f9b17a] flex items-center justify-center shadow-lg">
                <Star className={`w-12 h-12 ${getRatingColor(session.feedback.rating)} fill-current`} />
              </div>
              <div>
                <div className="flex items-baseline gap-2 mb-2">
                  <span className={`text-7xl font-bold tracking-tighter ${getRatingColor(session.feedback.rating)}`}>
                    {session.feedback.rating}
                  </span>
                  <span className="text-3xl text-[#adb5bd] font-light">/10</span>
                </div>
                <p className={`text-lg font-semibold ${getRatingColor(session.feedback.rating)}`}>
                  {getRatingLabel(session.feedback.rating)}
                </p>
              </div>
            </div>
            <div className="text-center md:text-right">
              <p className="text-sm text-[#adb5bd] font-medium mb-1">
                Completed
              </p>
              <p className="text-[#2d3250] font-medium">
                {new Date(session.createdAt).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </p>
              <p className="text-[#676f9d] text-sm">
                {new Date(session.createdAt).toLocaleTimeString("en-US", {
                  hour: "2-digit",
                  minute: "2-digit",
                })}
              </p>
            </div>
          </div>
        </div>

        {/* Advanced Score Breakdown */}
        {(session.feedback.technicalScore || session.feedback.problemSolvingScore || session.feedback.communicationScore) && (
          <div className="bg-white border-2 border-[#e9ecef] rounded-3xl overflow-hidden mb-8 shadow-lg">
            <div className="border-b-2 border-[#e9ecef] p-6 bg-gradient-to-r from-[#f8f9fa] to-white">
              <h2 className="text-2xl font-bold text-[#2d3250]">Performance Metrics</h2>
            </div>
            <div className="grid md:grid-cols-3 divide-x-2 divide-[#e9ecef]">
              {/* Technical Score */}
              {session.feedback.technicalScore !== undefined && (
                <div className="p-8 relative group hover:bg-[#f8f9fa] transition-colors">
                  <p className="text-xs font-semibold text-[#adb5bd] mb-6">TECHNICAL KNOWLEDGE</p>
                  <div className="mb-6">
                    <div className="flex items-baseline gap-3 mb-2">
                      <span className={`text-6xl font-bold tracking-tighter ${getScoreTextColor(session.feedback.technicalScore)}`}>
                        {session.feedback.technicalScore}
                      </span>
                      <span className="text-2xl text-[#adb5bd] font-light">/10</span>
                    </div>
                  </div>
                  <div className="space-y-2">
                    {Array.from({ length: 10 }).map((_, i) => (
                      <div
                        key={i}
                        className={`h-2 rounded-full ${
                          i < session.feedback.technicalScore!
                            ? getScoreColor(session.feedback.technicalScore!)
                            : 'bg-[#e9ecef]'
                        }`}
                      ></div>
                    ))}
                  </div>
                </div>
              )}

              {/* Problem Solving Score */}
              {session.feedback.problemSolvingScore !== undefined && (
                <div className="p-8 relative group hover:bg-[#f8f9fa] transition-colors">
                  <p className="text-xs font-semibold text-[#adb5bd] mb-6">PROBLEM SOLVING</p>
                  <div className="mb-6">
                    <div className="flex items-baseline gap-3 mb-2">
                      <span className={`text-6xl font-bold tracking-tighter ${getScoreTextColor(session.feedback.problemSolvingScore)}`}>
                        {session.feedback.problemSolvingScore}
                      </span>
                      <span className="text-2xl text-[#adb5bd] font-light">/10</span>
                    </div>
                  </div>
                  <div className="space-y-2">
                    {Array.from({ length: 10 }).map((_, i) => (
                      <div
                        key={i}
                        className={`h-2 rounded-full ${
                          i < session.feedback.problemSolvingScore!
                            ? getScoreColor(session.feedback.problemSolvingScore!)
                            : 'bg-[#e9ecef]'
                        }`}
                      ></div>
                    ))}
                  </div>
                </div>
              )}

              {/* Communication Score */}
              {session.feedback.communicationScore !== undefined && (
                <div className="p-8 relative group hover:bg-[#f8f9fa] transition-colors">
                  <p className="text-xs font-semibold text-[#adb5bd] mb-6">COMMUNICATION</p>
                  <div className="mb-6">
                    <div className="flex items-baseline gap-3 mb-2">
                      <span className={`text-6xl font-bold tracking-tighter ${getScoreTextColor(session.feedback.communicationScore)}`}>
                        {session.feedback.communicationScore}
                      </span>
                      <span className="text-2xl text-[#adb5bd] font-light">/10</span>
                    </div>
                  </div>
                  <div className="space-y-2">
                    {Array.from({ length: 10 }).map((_, i) => (
                      <div
                        key={i}
                        className={`h-2 rounded-full ${
                          i < session.feedback.communicationScore!
                            ? getScoreColor(session.feedback.communicationScore!)
                            : 'bg-[#e9ecef]'
                        }`}
                      ></div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Overall Assessment */}
        <div className="bg-white border-2 border-[#e9ecef] rounded-3xl overflow-hidden mb-8 shadow-lg">
          <div className="border-b-2 border-[#e9ecef] p-6 flex items-center gap-4 bg-gradient-to-r from-[#f8f9fa] to-white">
            <div className="w-10 h-10 bg-[#424769] rounded-xl flex items-center justify-center">
              <FileText className="w-5 h-5 text-white" />
            </div>
            <h2 className="text-2xl font-bold text-[#2d3250]">Overall Assessment</h2>
          </div>
          <div className="p-8">
            <p className="text-[#676f9d] leading-relaxed text-base whitespace-pre-wrap">
              {session.feedback.overall}
            </p>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-8">
          {/* Strengths */}
          <div className="bg-white border-2 border-[#10b981]/30 rounded-3xl overflow-hidden shadow-lg">
            <div className="border-b-2 border-[#10b981]/30 p-6 flex items-center justify-between bg-[#10b981]/5">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-[#10b981] rounded-xl flex items-center justify-center shadow-md">
                  <TrendingUp className="w-5 h-5 text-white" />
                </div>
                <h2 className="text-xl font-bold text-[#2d3250]">Strengths</h2>
              </div>
              {session.feedback.strengths && session.feedback.strengths.length > 0 && (
                <span className="text-xs font-semibold text-[#10b981] bg-[#10b981]/10 px-3 py-1 rounded-full">
                  {session.feedback.strengths.length}
                </span>
              )}
            </div>
            <div className="p-6">
              {session.feedback.strengths && session.feedback.strengths.length > 0 ? (
                <ul className="space-y-4">
                  {session.feedback.strengths.map((strength, index) => (
                    <li key={index} className="flex items-start gap-4 group">
                      <div className="flex-shrink-0 mt-1">
                        <div className="w-6 h-6 bg-[#10b981] rounded-full flex items-center justify-center shadow-sm">
                          <CheckCircle className="w-4 h-4 text-white" />
                        </div>
                      </div>
                      <span className="text-[#676f9d] leading-relaxed">{strength}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-[#adb5bd] italic">No specific strengths noted</p>
              )}
            </div>
          </div>

          {/* Weaknesses */}
          <div className="bg-white border-2 border-[#ef4444]/30 rounded-3xl overflow-hidden shadow-lg">
            <div className="border-b-2 border-[#ef4444]/30 p-6 flex items-center justify-between bg-[#ef4444]/5">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-[#ef4444] rounded-xl flex items-center justify-center shadow-md">
                  <TrendingDown className="w-5 h-5 text-white" />
                </div>
                <h2 className="text-xl font-bold text-[#2d3250]">Areas to Improve</h2>
              </div>
              {session.feedback.weaknesses && session.feedback.weaknesses.length > 0 && (
                <span className="text-xs font-semibold text-[#ef4444] bg-[#ef4444]/10 px-3 py-1 rounded-full">
                  {session.feedback.weaknesses.length}
                </span>
              )}
            </div>
            <div className="p-6">
              {session.feedback.weaknesses && session.feedback.weaknesses.length > 0 ? (
                <ul className="space-y-4">
                  {session.feedback.weaknesses.map((weakness, index) => (
                    <li key={index} className="flex items-start gap-4 group">
                      <div className="flex-shrink-0 mt-1">
                        <div className="w-6 h-6 bg-[#ef4444] rounded-full flex items-center justify-center shadow-sm">
                          <XCircle className="w-4 h-4 text-white" />
                        </div>
                      </div>
                      <span className="text-[#676f9d] leading-relaxed">{weakness}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-[#adb5bd] italic">No specific weaknesses noted</p>
              )}
            </div>
          </div>
        </div>

        {/* Suggestions */}
        <div className="bg-white border-2 border-[#f9b17a]/30 rounded-3xl overflow-hidden mb-8 shadow-lg">
          <div className="border-b-2 border-[#f9b17a]/30 p-6 flex items-center gap-4 bg-[#f9b17a]/5">
            <div className="w-10 h-10 bg-[#f9b17a] rounded-xl flex items-center justify-center shadow-md">
              <Lightbulb className="w-5 h-5 text-white" />
            </div>
            <h2 className="text-2xl font-bold text-[#2d3250]">Recommendations</h2>
          </div>
          <div className="p-8">
            <p className="text-[#676f9d] leading-relaxed text-base whitespace-pre-wrap">
              {session.feedback.suggestions}
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="bg-white border-2 border-[#e9ecef] rounded-3xl p-8 shadow-lg">
          <div className="grid md:grid-cols-3 gap-4">
            <button
              onClick={() => router.push("/session/new")}
              className="p-8 border-2 border-[#f9b17a] bg-[#f9b17a]/5 hover:bg-[#f9b17a] text-[#f9b17a] hover:text-white transition-all group rounded-2xl"
            >
              <div className="flex flex-col items-center gap-4">
                <div className="w-14 h-14 bg-[#f9b17a] group-hover:bg-white rounded-xl flex items-center justify-center transition-colors shadow-md">
                  <span className="text-3xl text-white group-hover:text-[#f9b17a] font-bold">+</span>
                </div>
                <span className="font-bold text-base">New Interview</span>
              </div>
            </button>
            <button
              onClick={() => router.push(`/interview/${sessionId}`)}
              className="p-8 border-2 border-[#e9ecef] hover:border-[#676f9d] hover:bg-[#676f9d]/5 text-[#676f9d] transition-all group rounded-2xl"
            >
              <div className="flex flex-col items-center gap-4">
                <div className="w-14 h-14 bg-[#676f9d]/10 group-hover:bg-[#676f9d] rounded-xl flex items-center justify-center transition-colors">
                  <FileText className="w-7 h-7 text-[#676f9d] group-hover:text-white" />
                </div>
                <span className="font-bold text-base">Review Transcript</span>
              </div>
            </button>
            <button
              onClick={() => router.push("/dashboard")}
              className="p-8 border-2 border-[#e9ecef] hover:border-[#424769] hover:bg-[#424769]/5 text-[#424769] transition-all group rounded-2xl"
            >
              <div className="flex flex-col items-center gap-4">
                <div className="w-14 h-14 bg-[#424769]/10 group-hover:bg-[#424769] rounded-xl flex items-center justify-center transition-colors">
                  <Home className="w-7 h-7 text-[#424769] group-hover:text-white" />
                </div>
                <span className="font-bold text-base">Dashboard</span>
              </div>
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
