"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import {
  ArrowLeft,
  TrendingUp,
  TrendingDown,
  Star,
  FileText,
  CheckCircle,
  XCircle,
  Lightbulb,
  Download,
  Home,
} from "lucide-react";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api";

interface Feedback {
  overall: string;
  strengths: string[];
  weaknesses: string[];
  rating: number;
  suggestions: string;
}

interface Session {
  _id: string;
  jobDetails: {
    title: string;
    description: string;
    yoeRequired: string;
  };
  status: string;
  feedback: Feedback;
  createdAt: string;
  conversation: Array<{
    role: string;
    content: string;
    timestamp: string;
  }>;
}

export default function FeedbackPage() {
  const router = useRouter();
  const params = useParams();
  const sessionId = params.sessionId as string;

  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const getAuthToken = () => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("accessToken");
    }
    return null;
  };

  const fetchSessionFeedback = async () => {
    try {
      const token = getAuthToken();
      if (!token) {
        router.push("/login");
        return;
      }

      const response = await fetch(`${API_BASE}/sessions/${sessionId}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (response.status === 401) {
        localStorage.removeItem("accessToken");
        localStorage.removeItem("refreshToken");
        router.push("/login");
        return;
      }

      if (!response.ok) {
        throw new Error("Failed to fetch feedback");
      }

      const data = await response.json();

      if (data.status !== "completed") {
        setError("This interview has not been completed yet");
        return;
      }

      if (!data.feedback) {
        setError("Feedback is not available for this session");
        return;
      }

      setSession(data);
    } catch (err: any) {
      setError(err.message || "Failed to load feedback");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (sessionId) {
      fetchSessionFeedback();
    }
  }, [sessionId]);

  const getRatingColor = (rating: number) => {
    if (rating >= 8) return "text-green-500";
    if (rating >= 6) return "text-yellow-500";
    if (rating >= 4) return "text-orange-500";
    return "text-red-500";
  };

  const getRatingLabel = (rating: number) => {
    if (rating >= 9) return "Excellent";
    if (rating >= 8) return "Very Good";
    if (rating >= 7) return "Good";
    if (rating >= 6) return "Above Average";
    if (rating >= 5) return "Average";
    if (rating >= 4) return "Below Average";
    if (rating >= 3) return "Needs Improvement";
    return "Poor";
  };

  const downloadFeedback = () => {
    if (!session) return;

    const feedbackText = `
Interview Feedback Report
========================

Position: ${session.jobDetails.title}
Date: ${new Date(session.createdAt).toLocaleDateString()}
Overall Rating: ${session.feedback.rating}/10 - ${getRatingLabel(session.feedback.rating)}

OVERALL ASSESSMENT
-----------------
${session.feedback.overall}

STRENGTHS
---------
${session.feedback.strengths.map((s, i) => `${i + 1}. ${s}`).join("\n")}

AREAS FOR IMPROVEMENT
--------------------
${session.feedback.weaknesses.map((w, i) => `${i + 1}. ${w}`).join("\n")}

SUGGESTIONS FOR IMPROVEMENT
---------------------------
${session.feedback.suggestions}

---
Generated by AI Mock Interview Platform
    `.trim();

    const blob = new Blob([feedbackText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `interview-feedback-${sessionId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-500 mx-auto mb-4"></div>
          <p className="text-xl">Loading feedback...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="text-center max-w-md">
          <XCircle className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold mb-4">Error</h2>
          <p className="text-gray-400 mb-6">{error}</p>
          <button
            onClick={() => router.push("/dashboard")}
            className="px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors"
          >
            Return to Dashboard
          </button>
        </div>
      </div>
    );
  }

  if (!session) {
    return null;
  }

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <header className="border-b border-gray-800 bg-black/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <button
              onClick={() => router.push("/dashboard")}
              className="p-2 hover:bg-gray-800 rounded-lg transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-2xl font-bold">Interview Feedback</h1>
              <p className="text-sm text-gray-400">{session.jobDetails.title}</p>
            </div>
          </div>
          <div className="flex gap-3">
            <button
              onClick={downloadFeedback}
              className="px-4 py-2 bg-gray-800 hover:bg-gray-700 rounded-lg transition-colors flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
            <button
              onClick={() => router.push("/dashboard")}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors flex items-center gap-2"
            >
              <Home className="w-4 h-4" />
              Dashboard
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-12">
        {/* Rating Card */}
        <div className="bg-gradient-to-br from-gray-900 to-black border border-gray-800 rounded-2xl p-8 mb-8 text-center">
          <div className="flex items-center justify-center gap-3 mb-4">
            <Star className={`w-12 h-12 ${getRatingColor(session.feedback.rating)} fill-current`} />
            <div>
              <div className={`text-6xl font-bold ${getRatingColor(session.feedback.rating)}`}>
                {session.feedback.rating}
                <span className="text-3xl text-gray-500">/10</span>
              </div>
              <p className={`text-xl font-semibold ${getRatingColor(session.feedback.rating)}`}>
                {getRatingLabel(session.feedback.rating)}
              </p>
            </div>
          </div>
          <p className="text-sm text-gray-400">
            Interview completed on {new Date(session.createdAt).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
              hour: "2-digit",
              minute: "2-digit",
            })}
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-8">
          {/* Overall Assessment */}
          <div className="md:col-span-2 bg-gradient-to-br from-gray-900 to-black border border-gray-800 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-blue-600/20 rounded-lg">
                <FileText className="w-6 h-6 text-blue-500" />
              </div>
              <h2 className="text-2xl font-bold">Overall Assessment</h2>
            </div>
            <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">
              {session.feedback.overall}
            </p>
          </div>

          {/* Strengths */}
          <div className="bg-gradient-to-br from-gray-900 to-black border border-gray-800 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-green-600/20 rounded-lg">
                <TrendingUp className="w-6 h-6 text-green-500" />
              </div>
              <h2 className="text-2xl font-bold">Strengths</h2>
            </div>
            {session.feedback.strengths && session.feedback.strengths.length > 0 ? (
              <ul className="space-y-3">
                {session.feedback.strengths.map((strength, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                    <span className="text-gray-300">{strength}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-gray-500 italic">No specific strengths noted</p>
            )}
          </div>

          {/* Weaknesses */}
          <div className="bg-gradient-to-br from-gray-900 to-black border border-gray-800 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-red-600/20 rounded-lg">
                <TrendingDown className="w-6 h-6 text-red-500" />
              </div>
              <h2 className="text-2xl font-bold">Areas for Improvement</h2>
            </div>
            {session.feedback.weaknesses && session.feedback.weaknesses.length > 0 ? (
              <ul className="space-y-3">
                {session.feedback.weaknesses.map((weakness, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <XCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
                    <span className="text-gray-300">{weakness}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-gray-500 italic">No specific weaknesses noted</p>
            )}
          </div>

          {/* Suggestions */}
          <div className="md:col-span-2 bg-gradient-to-br from-gray-900 to-black border border-gray-800 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-yellow-600/20 rounded-lg">
                <Lightbulb className="w-6 h-6 text-yellow-500" />
              </div>
              <h2 className="text-2xl font-bold">Suggestions for Improvement</h2>
            </div>
            <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">
              {session.feedback.suggestions}
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 justify-center">
          <button
            onClick={() => router.push("/session/new")}
            className="px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors font-medium"
          >
            Start New Interview
          </button>
          <button
            onClick={() => router.push(`/interview/${sessionId}`)}
            className="px-6 py-3 bg-gray-700 hover:bg-gray-600 rounded-lg transition-colors font-medium"
          >
            Review Interview
          </button>
          <button
            onClick={() => router.push("/dashboard")}
            className="px-6 py-3 bg-gray-800 hover:bg-gray-700 rounded-lg transition-colors font-medium"
          >
            Back to Dashboard
          </button>
        </div>
      </main>
    </div>
  );
}
