"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import {
  ArrowLeft,
  TrendingUp,
  TrendingDown,
  Star,
  FileText,
  CheckCircle,
  XCircle,
  Lightbulb,
  Download,
  Home,
} from "lucide-react";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api";

interface Feedback {
  overall: string;
  strengths: string[];
  weaknesses: string[];
  rating: number;
  technicalScore?: number;
  problemSolvingScore?: number;
  communicationScore?: number;
  suggestions: string;
}

interface Session {
  _id: string;
  jobDetails: {
    title: string;
    description: string;
    yoeRequired: string;
  };
  status: string;
  feedback: Feedback;
  createdAt: string;
  conversation: Array<{
    role: string;
    content: string;
    timestamp: string;
  }>;
}

export default function FeedbackPage() {
  const router = useRouter();
  const params = useParams();
  const sessionId = params.sessionId as string;

  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const getAuthToken = () => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("accessToken");
    }
    return null;
  };

  const fetchSessionFeedback = async () => {
    try {
      const token = getAuthToken();
      if (!token) {
        router.push("/login");
        return;
      }

      const response = await fetch(`${API_BASE}/sessions/${sessionId}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (response.status === 401) {
        localStorage.removeItem("accessToken");
        localStorage.removeItem("refreshToken");
        router.push("/login");
        return;
      }

      if (!response.ok) {
        throw new Error("Failed to fetch feedback");
      }

      const data = await response.json();

      if (data.status !== "completed") {
        setError("This interview has not been completed yet");
        return;
      }

      if (!data.feedback) {
        setError("Feedback is not available for this session");
        return;
      }

      setSession(data);
    } catch (err: any) {
      setError(err.message || "Failed to load feedback");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (sessionId) {
      fetchSessionFeedback();
    }
  }, [sessionId]);

  const getRatingColor = (rating: number) => {
    if (rating >= 8) return "text-green-500";
    if (rating >= 6) return "text-yellow-500";
    if (rating >= 4) return "text-orange-500";
    return "text-red-500";
  };

  const getRatingLabel = (rating: number) => {
    if (rating >= 9) return "Excellent";
    if (rating >= 8) return "Very Good";
    if (rating >= 7) return "Good";
    if (rating >= 6) return "Above Average";
    if (rating >= 5) return "Average";
    if (rating >= 4) return "Below Average";
    if (rating >= 3) return "Needs Improvement";
    return "Poor";
  };

  const getScoreColor = (score: number) => {
    if (score >= 8) return "bg-green-500";
    if (score >= 6) return "bg-yellow-500";
    if (score >= 4) return "bg-orange-500";
    return "bg-red-500";
  };

  const getScoreTextColor = (score: number) => {
    if (score >= 8) return "text-green-500";
    if (score >= 6) return "text-yellow-500";
    if (score >= 4) return "text-orange-500";
    return "text-red-500";
  };

  const downloadFeedback = () => {
    if (!session) return;

    const advancedScores = session.feedback.technicalScore || session.feedback.problemSolvingScore || session.feedback.communicationScore
      ? `
DETAILED SCORES
---------------
${session.feedback.technicalScore ? `Technical Knowledge: ${session.feedback.technicalScore}/10` : ''}
${session.feedback.problemSolvingScore ? `Problem Solving: ${session.feedback.problemSolvingScore}/10` : ''}
${session.feedback.communicationScore ? `Communication: ${session.feedback.communicationScore}/10` : ''}
` : '';

    const feedbackText = `
Interview Feedback Report
========================

Position: ${session.jobDetails.title}
Date: ${new Date(session.createdAt).toLocaleDateString()}
Overall Rating: ${session.feedback.rating}/10 - ${getRatingLabel(session.feedback.rating)}
${advancedScores}
OVERALL ASSESSMENT
-----------------
${session.feedback.overall}

STRENGTHS
---------
${session.feedback.strengths.map((s, i) => `${i + 1}. ${s}`).join("\n")}

AREAS FOR IMPROVEMENT
--------------------
${session.feedback.weaknesses.map((w, i) => `${i + 1}. ${w}`).join("\n")}

SUGGESTIONS FOR IMPROVEMENT
---------------------------
${session.feedback.suggestions}

---
Generated by AI Mock Interview Platform
    `.trim();

    const blob = new Blob([feedbackText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `interview-feedback-${sessionId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="border-2 border-white/10 p-12">
          <div className="text-center">
            <div className="w-16 h-16 border-4 border-white/20 border-t-white mx-auto mb-6 animate-spin"></div>
            <p className="text-xl font-mono uppercase tracking-wider text-white/60">Loading feedback...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center p-6">
        <div className="border-2 border-red-500/50 max-w-md w-full">
          <div className="border-b-2 border-red-500/50 p-6 flex items-center gap-4">
            <div className="w-12 h-12 border-2 border-red-500/50 flex items-center justify-center">
              <XCircle className="w-6 h-6 text-red-500" />
            </div>
            <h2 className="text-2xl font-bold uppercase tracking-tight">Error</h2>
          </div>
          <div className="p-8">
            <p className="text-white/70 mb-8 leading-relaxed">{error}</p>
            <button
              onClick={() => router.push("/dashboard")}
              className="w-full p-4 border-2 border-white hover:bg-white hover:text-black transition-all font-bold uppercase tracking-wider"
            >
              Return to Dashboard
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!session) {
    return null;
  }

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <header className="border-b-2 border-white/10 sticky top-0 z-10 bg-black">
        <div className="max-w-7xl mx-auto px-6 py-6 flex justify-between items-center">
          <div className="flex items-center gap-6">
            <button
              onClick={() => router.push("/dashboard")}
              className="p-3 border-2 border-white/20 hover:border-white hover:bg-white hover:text-black transition-all"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-3xl font-bold tracking-tight">Feedback</h1>
              <p className="text-sm text-white/50 mt-1 font-mono">{session.jobDetails.title}</p>
            </div>
          </div>
          <div className="flex gap-3">
            <button
              onClick={downloadFeedback}
              className="px-5 py-3 border-2 border-white/20 hover:border-white hover:bg-white hover:text-black transition-all flex items-center gap-2 font-medium"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Download</span>
            </button>
            <button
              onClick={() => router.push("/dashboard")}
              className="px-5 py-3 bg-white text-black hover:bg-white/90 transition-all flex items-center gap-2 font-medium"
            >
              <Home className="w-4 h-4" />
              <span className="hidden sm:inline">Dashboard</span>
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-16">
        {/* Rating Card */}
        <div className="border-2 border-white/10 p-12 mb-12 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 border-l-2 border-b-2 border-white/5"></div>
          <div className="absolute bottom-0 left-0 w-32 h-32 border-r-2 border-t-2 border-white/5"></div>

          <div className="flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="flex items-center gap-6">
              <div className="w-24 h-24 border-4 border-white/20 flex items-center justify-center">
                <Star className={`w-12 h-12 ${getRatingColor(session.feedback.rating)} fill-current`} />
              </div>
              <div>
                <div className="flex items-baseline gap-2 mb-2">
                  <span className={`text-7xl font-bold tracking-tighter ${getRatingColor(session.feedback.rating)}`}>
                    {session.feedback.rating}
                  </span>
                  <span className="text-3xl text-white/30 font-light">/10</span>
                </div>
                <p className={`text-lg font-medium ${getRatingColor(session.feedback.rating)} uppercase tracking-wider`}>
                  {getRatingLabel(session.feedback.rating)}
                </p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-sm text-white/40 font-mono uppercase tracking-wider">
                Completed
              </p>
              <p className="text-white/70 mt-1 font-mono">
                {new Date(session.createdAt).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "short",
                  day: "numeric",
                })}
              </p>
              <p className="text-white/50 text-sm font-mono">
                {new Date(session.createdAt).toLocaleTimeString("en-US", {
                  hour: "2-digit",
                  minute: "2-digit",
                })}
              </p>
            </div>
          </div>
        </div>

        {/* Advanced Score Breakdown */}
        {(session.feedback.technicalScore || session.feedback.problemSolvingScore || session.feedback.communicationScore) && (
          <div className="border-2 border-white/10 mb-12">
            <div className="border-b-2 border-white/10 p-6">
              <h2 className="text-2xl font-bold tracking-tight uppercase">Performance Metrics</h2>
            </div>
            <div className="grid md:grid-cols-3 divide-x-2 divide-white/10">
              {/* Technical Score */}
              {session.feedback.technicalScore !== undefined && (
                <div className="p-8 relative group hover:bg-white/5 transition-colors">
                  <div className="absolute top-4 right-4 w-12 h-12 border-2 border-white/10"></div>
                  <p className="text-xs font-mono text-white/40 uppercase tracking-widest mb-6">01</p>
                  <div className="mb-8">
                    <div className="flex items-baseline gap-3 mb-3">
                      <span className={`text-6xl font-bold tracking-tighter ${getScoreTextColor(session.feedback.technicalScore)}`}>
                        {session.feedback.technicalScore}
                      </span>
                      <span className="text-2xl text-white/20 font-light">/10</span>
                    </div>
                    <p className="text-sm font-medium text-white/60 uppercase tracking-wider">Technical</p>
                  </div>
                  <div className="space-y-1">
                    {Array.from({ length: 10 }).map((_, i) => (
                      <div
                        key={i}
                        className={`h-1 ${
                          i < session.feedback.technicalScore!
                            ? getScoreColor(session.feedback.technicalScore!)
                            : 'bg-white/10'
                        }`}
                      ></div>
                    ))}
                  </div>
                </div>
              )}

              {/* Problem Solving Score */}
              {session.feedback.problemSolvingScore !== undefined && (
                <div className="p-8 relative group hover:bg-white/5 transition-colors">
                  <div className="absolute top-4 right-4 w-12 h-12 border-2 border-white/10"></div>
                  <p className="text-xs font-mono text-white/40 uppercase tracking-widest mb-6">02</p>
                  <div className="mb-8">
                    <div className="flex items-baseline gap-3 mb-3">
                      <span className={`text-6xl font-bold tracking-tighter ${getScoreTextColor(session.feedback.problemSolvingScore)}`}>
                        {session.feedback.problemSolvingScore}
                      </span>
                      <span className="text-2xl text-white/20 font-light">/10</span>
                    </div>
                    <p className="text-sm font-medium text-white/60 uppercase tracking-wider">Problem Solving</p>
                  </div>
                  <div className="space-y-1">
                    {Array.from({ length: 10 }).map((_, i) => (
                      <div
                        key={i}
                        className={`h-1 ${
                          i < session.feedback.problemSolvingScore!
                            ? getScoreColor(session.feedback.problemSolvingScore!)
                            : 'bg-white/10'
                        }`}
                      ></div>
                    ))}
                  </div>
                </div>
              )}

              {/* Communication Score */}
              {session.feedback.communicationScore !== undefined && (
                <div className="p-8 relative group hover:bg-white/5 transition-colors">
                  <div className="absolute top-4 right-4 w-12 h-12 border-2 border-white/10"></div>
                  <p className="text-xs font-mono text-white/40 uppercase tracking-widest mb-6">03</p>
                  <div className="mb-8">
                    <div className="flex items-baseline gap-3 mb-3">
                      <span className={`text-6xl font-bold tracking-tighter ${getScoreTextColor(session.feedback.communicationScore)}`}>
                        {session.feedback.communicationScore}
                      </span>
                      <span className="text-2xl text-white/20 font-light">/10</span>
                    </div>
                    <p className="text-sm font-medium text-white/60 uppercase tracking-wider">Communication</p>
                  </div>
                  <div className="space-y-1">
                    {Array.from({ length: 10 }).map((_, i) => (
                      <div
                        key={i}
                        className={`h-1 ${
                          i < session.feedback.communicationScore!
                            ? getScoreColor(session.feedback.communicationScore!)
                            : 'bg-white/10'
                        }`}
                      ></div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Overall Assessment */}
        <div className="border-2 border-white/10 mb-8">
          <div className="border-b-2 border-white/10 p-6 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 border-2 border-white/30 flex items-center justify-center">
                <FileText className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold tracking-tight uppercase">Assessment</h2>
            </div>
          </div>
          <div className="p-8">
            <p className="text-white/70 leading-relaxed text-lg whitespace-pre-wrap">
              {session.feedback.overall}
            </p>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-8 mb-8">
          {/* Strengths */}
          <div className="border-2 border-white/10">
            <div className="border-b-2 border-white/10 p-6 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 border-2 border-green-500/50 flex items-center justify-center">
                  <TrendingUp className="w-5 h-5 text-green-500" />
                </div>
                <h2 className="text-xl font-bold tracking-tight uppercase">Strengths</h2>
              </div>
              {session.feedback.strengths && session.feedback.strengths.length > 0 && (
                <span className="text-xs font-mono text-white/40 tracking-widest">
                  {session.feedback.strengths.length} ITEMS
                </span>
              )}
            </div>
            <div className="p-6">
              {session.feedback.strengths && session.feedback.strengths.length > 0 ? (
                <ul className="space-y-4">
                  {session.feedback.strengths.map((strength, index) => (
                    <li key={index} className="flex items-start gap-4 group">
                      <div className="flex-shrink-0 mt-1">
                        <div className="w-6 h-6 border-2 border-green-500/50 flex items-center justify-center group-hover:bg-green-500/10 transition-colors">
                          <CheckCircle className="w-4 h-4 text-green-500" />
                        </div>
                      </div>
                      <span className="text-white/70 leading-relaxed">{strength}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-white/30 italic">No specific strengths noted</p>
              )}
            </div>
          </div>

          {/* Weaknesses */}
          <div className="border-2 border-white/10">
            <div className="border-b-2 border-white/10 p-6 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 border-2 border-red-500/50 flex items-center justify-center">
                  <TrendingDown className="w-5 h-5 text-red-500" />
                </div>
                <h2 className="text-xl font-bold tracking-tight uppercase">Areas to Improve</h2>
              </div>
              {session.feedback.weaknesses && session.feedback.weaknesses.length > 0 && (
                <span className="text-xs font-mono text-white/40 tracking-widest">
                  {session.feedback.weaknesses.length} ITEMS
                </span>
              )}
            </div>
            <div className="p-6">
              {session.feedback.weaknesses && session.feedback.weaknesses.length > 0 ? (
                <ul className="space-y-4">
                  {session.feedback.weaknesses.map((weakness, index) => (
                    <li key={index} className="flex items-start gap-4 group">
                      <div className="flex-shrink-0 mt-1">
                        <div className="w-6 h-6 border-2 border-red-500/50 flex items-center justify-center group-hover:bg-red-500/10 transition-colors">
                          <XCircle className="w-4 h-4 text-red-500" />
                        </div>
                      </div>
                      <span className="text-white/70 leading-relaxed">{weakness}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-white/30 italic">No specific weaknesses noted</p>
              )}
            </div>
          </div>
        </div>

        {/* Suggestions */}
        <div className="border-2 border-white/10 mb-12">
          <div className="border-b-2 border-white/10 p-6 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 border-2 border-yellow-500/50 flex items-center justify-center">
                <Lightbulb className="w-5 h-5 text-yellow-500" />
              </div>
              <h2 className="text-2xl font-bold tracking-tight uppercase">Recommendations</h2>
            </div>
          </div>
          <div className="p-8">
            <p className="text-white/70 leading-relaxed text-lg whitespace-pre-wrap">
              {session.feedback.suggestions}
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="border-2 border-white/10 p-8">
          <div className="grid md:grid-cols-3 gap-4">
            <button
              onClick={() => router.push("/session/new")}
              className="p-6 border-2 border-white hover:bg-white hover:text-black transition-all group"
            >
              <div className="flex flex-col items-center gap-3">
                <div className="w-12 h-12 border-2 border-white/30 group-hover:border-black flex items-center justify-center transition-colors">
                  <span className="text-2xl">+</span>
                </div>
                <span className="font-bold uppercase tracking-wider text-sm">New Interview</span>
              </div>
            </button>
            <button
              onClick={() => router.push(`/interview/${sessionId}`)}
              className="p-6 border-2 border-white/20 hover:border-white hover:bg-white/5 transition-all group"
            >
              <div className="flex flex-col items-center gap-3">
                <div className="w-12 h-12 border-2 border-white/30 flex items-center justify-center">
                  <FileText className="w-6 h-6" />
                </div>
                <span className="font-bold uppercase tracking-wider text-sm">Review Transcript</span>
              </div>
            </button>
            <button
              onClick={() => router.push("/dashboard")}
              className="p-6 border-2 border-white/20 hover:border-white hover:bg-white/5 transition-all group"
            >
              <div className="flex flex-col items-center gap-3">
                <div className="w-12 h-12 border-2 border-white/30 flex items-center justify-center">
                  <Home className="w-6 h-6" />
                </div>
                <span className="font-bold uppercase tracking-wider text-sm">Dashboard</span>
              </div>
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
